### ISSUE TITLE
Add support for SameSite=None; Secure

### ISSUE THREAD

**Issue by 9mido** [jotes/django-cookies-samesite#23]
https://web.dev/samesite-cookie-recipes/

https://blog.chromium.org/2019/10/developers-get-ready-for-new.html

https://digiday.com/media/what-is-chrome-samesite/

**Comment by abdul-rafiu** [comment]
Hi, implemented this in this PR - https://github.com/jotes/django-cookies-samesite/pull/24

**Comment by jotes** [comment]
Was fixed in https://github.com/jotes/django-cookies-samesite/pull/24

**Comment by caryyu** [comment]
What if I have an API-gateway in front with https, but the http is still in django itself behind that gateway, which will still not work.

Fortunately, there's an alternative to this: https://github.com/zvyn/django-samesite-none
